spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ems
    password: ems
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database: oracle
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: zashu1077@gmail.com
    password: yszg isrn hths jtph
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
server:
  port: 8082
